name: auto changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    # 只在非 oasis 定制版 tag 时运行
    if: "!contains(github.ref, '-oasis')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete beta tag
        run: git tag -d beta
        continue-on-error: true

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
